#J vim:syntax=python
import os
import glob
import sys

cflags= ["-ggdb"]
Import('env')
conf = Configure(env)
conf.CheckLib('curl')
conf.env.Append(CFLAGS = cflags)
if conf.CheckLib('libxml2'):
	conf.env.Append(CFLAGS = ['-I/usr/include/libxml2'])
env = conf.Finish()

def do_header():
	header_dir = '/usr/local/include/libtwit'
	if not os.path.exists(header_dir):
		os.mkdir(header_dir)
	headers = ['core.h', 'status.h', 'account.h', 'output.h']
	for header in headers:
		env.Install(header_dir, header)

cfiles = ['core.c', 'status.c', 'account.c', 'output.c']
libtwit = env.SharedLibrary('libtwit', cfiles)

if len(sys.argv) > 1:
	if sys.argv[1] == "install":
		do_header()

env.Install('/usr/local/lib', libtwit)
env.Alias('install', ['/usr/local/lib', '/usr/local/include'])

